### ISSUE TITLE
GUI company ID tool

### ISSUE THREAD

**Issue by lassemoldrup** [Concordium/concordium-misc-tools#109]
The current way that companies create accounts is with the [`user-cli`](https://github.com/Concordium/concordium-base/blob/19649cfb17a84011bf71e46cb9d2bb00ced9e35f/rust-bins/docs/user-cli.md) CLI tool, which is not user friendly enough. We will therefore create a GUI version of this tool.

**Comment by abizjak** [comment]
The tool is released.
