### ISSUE TITLE
Update dApps to new web-sdk and wallet-api

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#110]
New versions of JS libraries have been published, which we should strive to use in our applications.

**Libraries to update:**

- `@concordium/web-sdk`
- `@concordium/react-components`
- `@concordium/wallet-connectors`
- `@concordium/browser-wallet-api-helpers`

**Applications needing updates**

- [ ] [id-verifier](https://github.com/Concordium/concordium-misc-tools/tree/main/id-verifier)
- [ ] [wallet-connect-test-bench](https://github.com/Concordium/concordium-misc-tools/tree/main/wallet-connect-test-bench)

**Comment by abizjak** [comment]
@soerenbf Is this done now or not? Can you please add some description if it is not?

**Comment by soerenbf** [comment]
@abizjak updated the description. I didn't get around to updating these when I updated most of our dapps as they're testing tools only.

If you want, we can just close the issue.

**Comment by abizjak** [comment]
No, let's leave the issue since work is needed. Thanks for adding details.
