### ISSUE TITLE
KPI Tracker - Selecting less than 24 hours for the range causes performance issues

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-misc-tools#112]
**Bug Description**
Selecting 12 hours for the range causes some performance issues such as transactions graphs are loaded slow and their responsiveness is also slow.

**Steps to Reproduce**
Open KPI Tracker Grafana page and select the range to be 12 hours.
Observe transactions graphs.

**Expected Result**
Performance should not be affected.

**Actual Result**
Currently it seems to take unusually longer time to load the graph.

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
This should be fixed now., based on my tests at least.
