### ISSUE TITLE
KPI Tracker - Foundation tax graph is missing CCD as the unit after the value

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-misc-tools#114]
**Bug Description**
Foundation tax graph is missing CCD as the unit after the value

**Steps to Reproduce**
Look at the Foundation Tax graph.

**Expected Result**
Should contain CCD as unit.

**Actual Result**
Doesn't contain any unit.

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
This is fixed now.
