### ISSUE TITLE
KPI Tracker - Combine old baker transaction types from Transactions graph into `configure_baker`

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-misc-tools#115]
**Bug Description**
Transactions graph offers possibility to filter by transactions that are no longer used. We should combine those transactions into the `Configure baker` for both Transactions graph and Transactions (Cumulative) graph.

Combine the following transaction types into configure_baker from Transactions and Transactions (cumulative) graph:

- add_baker
- remove_baker
- update_baker_stake
- update_baker_restake_earning
- update_baker_keys

**Another thing related to the Transactions graph** is that since it is "stacking type", it seems sometime visually a bit strange. For example if we select top show configure_baker and remove_baker for a range since 11-2021 to today, it visually looks as configure baker was used even before it was introduced. This is because when the value is 0, it seems that the type selected is just stacked on top of the other type selected. 

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
This is fixed in v2.
