### ISSUE TITLE
[ID proof explorer] Handle id proof request rejection from mobile wallet

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#22]
When the user rejects a request for an ID proof in the mobile wallet, the rejection is currently not handled in the proof explorer app.

It would be nice if this was the case, to align with how rejection is handled by the browser wallet, and to be able to test this scenario internally.

**Comment by abizjak** [comment]
What happens at the moment? Is there no indication of this? I assume they can recover by refreshing?

**Comment by soerenbf** [comment]
> What happens at the moment? Is there no indication of this? I assume they can recover by refreshing?

Yes, I also don't think this is a critical thing to solve, but it would be good with confirmation that the rejection can be received in the dapp-end.

**Comment by abizjak** [comment]
Yes, I agree with that. If it takes less than an hour we should just do it. This is relevant for testing the wallet.
