### ISSUE TITLE
Investigate which metrics to add to KPI tracker

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-misc-tools#87]
**Task description**

**Comment by lassemoldrup** [comment]
The requested additions are categorized into three categories depending on their diffulty. We will implement the first two categories.

No code change required:
- No. of new initial accounts
- No. of new accounts in total 
- No. of new accounts in existence
- No. of active accounts (Already there)
- No. of new active accounts
- No. of transactions (Already there)
- No. of CCDs paid as transaction fees (Already there)
- No. of smart contracts deployed (Already there)
- No. of active smart contracts (Already there)
- No. of CCDs staked (Already there)
- No. of CCD-transfer transactions
- No. of accounts with CCD-receive or CCD-send transactions 

DB/code change needed:
- No. of (new) active bakers
- No. of new CCDs minted
- No. of CCDs paid as baker rewards
- No. of CCDs paid as finaliser rewards
- No. of CCDs paid to Concordium Foundation as 10% charge
- No. of finalizers
- No. of CCDs delegated
- No. of bakers open for delegation
- No. of bakers actually receiving delegated CCDs
- No. of accounts staking
- No. of accounts delegating

Too much work right now:
- No. of active nodes
- No. of CCDs earned by bakers from delegation
